name: Run Build

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:
    inputs:
      skip_cdn_upload:
        description: 'Upload to CDN?'
        type: boolean
        default: false
      appName:
        description: 'Custom App Name'
        required: true
        default: 'AppName'
      

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Custom Name To Build
        run: echo "APP_NAME=${{ github.event.inputs.appName}}" >> $GITHUB_ENV
        #old versioning was only for linix, need to find another way
      - name: Upload to CDN
        if: ${{ github.event.inputs.skip_cdn_upload == 'true' }}
        run: echo "Uploading to CDN..."
      - name: Check on OS
        run: echo "This job is running on ${{ runner.os}}"
      - name: Creating Version Number
        run: echo "Getting version number"
      - uses: paulhatch/semantic-version@v5.4.0
        with:
            bump_each_commit: true
            bump_each_commit_patch_pattern: "(PATCH)"
          
        # Issue here was spaces between appName and "Test App" And removing $ in appName
        # needed Perms to make this work
      # CLI call to simulated build process
      - name: Run Build
        run: |
          chmod +x ./build.sh 
          ./build.sh --platform Android --project-name ${APP_NAME}
        
      # Issue below was because of a " not being closed.
      # CLI call to simulated upload process
      - name: Upload
        run: |
          chmod +x ./upload.sh

