name: Run Build

on:
  workflow_dispatch:
    inputs:
      appname:
        description: 'Custom App Name'
        required: true
        default: 'AppName'
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # Issue here was spaces between appName and "Test App" And removing $ in appName
        # needed Perms to make this work
      # CLI call to simulated build process
      - name: Run Build
        run: |
          chmod +x ./build.sh 
          ./build.sh --platform Android --project-name ${appname}
        
      # Issue below was because of a " not being closed.
      # CLI call to simulated upload process
      - name: Upload
        run: |
          chmod +x ./upload.sh
          
