name: Run Build

on:
  workflow_dispatch:
    inputs:
      skip_cdn_upload:
        description: 'Upload to CDN?'
        type: boolean
        default: false
      appName:
        description: 'Custom App Name'
        required: true
        default: 'AppName'
      

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Custom Name To Build
        run: echo "APP_NAME=${{ github.event.inputs.appName}}" >> $GITHUB_ENV
      - name: Git Version
            # You may pin to the exact commit or the version.
            # uses: codacy/git-version@fa06788276d7492a2af01662649696d249ecf4cb
        uses: codacy/git-version@2.4.0
        with:
            # The name of the release branch
            release-branch: Main # default is master
            # The name of the dev branch
            dev-branch: # default is dev
    # The paths to be used to calculate changes (comma-separated)
            log-paths:            
          
     
     
        # Issue here was spaces between appName and "Test App" And removing $ in appName
        # needed Perms to make this work
      # CLI call to simulated build process
      - name: Run Build
        run: |
          chmod +x ./build.sh 
          ./build.sh --platform Android --project-name ${APP_NAME}
        
      # Issue below was because of a " not being closed.
      # CLI call to simulated upload process
      - name: Upload
        run: |
          chmod +x ./upload.sh
          
